// <auto-generated />
namespace TST_Music_Instruments_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migrationsfortheuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrationsfortheuser));
        
        string IMigrationMetadata.Id
        {
            get { return "202102021821077_migrations for the user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
